workflows:
  hello-world:
    environment:
      groups:
        - example-group
      vars:
        SONAR_TOKEN: Encrypted(Z0FBQUFBQmhMNG5ITXR3NXhodFpwNkNFTHYwLTRtbDBGSXM0N0VselhfR1RYQWljODk5TmQ5NTE0bmVSREo0cmp2MC0xQW9jWURoTF92azQ2OGxhZHlzOWllQzFnVjdSb0NCem9YVy1CR0RZMmZHSTVNMGxOdEJPY2QyYTFlZl9zeGhaTzduWndKQTE=)
        SONAR_ORG_KEY: marcin-majewski-sonarsource-1
        SONAR_PROJECT_KEY: marcin-majewski-sonarsource_android-calculator
    name: Hello world workflow
    scripts:
        - ./gradlew assembleDebub        
        - |
        # Generate and upload code analysis report
        ./gradlew sonarqube \
        -Dsonar.projectKey=$SONAR_PROJECT_KEY \
        -Dsonar.organization=$SONAR_ORG_KEY \
        -Dsonar.host.url=https://mmsc.eu.ngrok.io \
        -Dsonar.login=$SONAR_TOKEN \